app:
  ERROR_STATUS: 400
  OK_STATUS: 200
  CAR_SEARCH_RADIUS_LIMIT: 500
  REQUEST_ID_LENGTH_LIMIT: 1000
  DEBUG: True

db:
  driver: '{SQL Server}'
  server: 10.42.0.1
  user: api-user
  password: c9NvVeEXTPUvzDAg
  database: rzdb
  encrypt: False